services:
  - type: worker
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: N8N_TUNNEL_SUBDOMAIN
        value: mymassabot
      - key: GENERIC_TIMEZONE
        value: Asia/Almaty
      - key: N8N_BASIC_AUTH_ACTIVE
        value: false